//! Chapter 2, Objects: the sentences that define and describe.

use super::{held, ran, rule, stated, Rule};

const RUN: &str = "Sentences02";

pub const SENTENCES: &[Rule] = &[
    // ---- 2.1 ----
    ran("02", "Every value is an instance of exactly one class", RUN, "classes: cleat.Int cleat.Char cleat.Boolean cleat.String cleat.Array<cleat.Int> null"),
    rule("02", "There are no primitive types", &[("class A { int x = 1; }", "`int` is a reserved word")], &["class A { Int x = 1; Int f() { return x.hashCode(); } }"]),
    ran("02", "are instances of classes that the prelude declares", RUN, "classes: cleat.Int cleat.Char cleat.Boolean cleat.String cleat.Array<cleat.Int> null"),
    stated("02", "A class is a reference class or a value class, as", "It points to section 2.3, whose sentences have their own cases."),
    ran("02", "The difference is whether its instances have identity", RUN, "value identity: true true"),
    stated("02", "How an implementation stores an instance is not observable", "It says what no program can observe."),
    held("02", "An operator is a method of its left operand, as", "spec_tables", "each_operator_of_section_4_6_is_its_method"),
    rule("02", "A missing method is a type error", &[("class P { } class A { void f(P p) { p.missing(); } }", "`P` has no method named `missing`"), ("class P { } class A { P f(P p) { return p * p; } }", "`P` has no method `times`")], &[]),
    // ---- 2.2 ----
    held("02", "The prelude is written in Cleat", "spec_rules", "the_prelude_is_source_the_checker_accepts"),
    rule(
        "02",
        "a class that a program declares may do whatever a prelude class does",
        &[],
        &["value class Money { public Int cents; public Money plus(Money o) { return new Money(cents + o.cents); } public Boolean lessThan(Money o) { return cents < o.cents; } } class A { Boolean f(Money a, Money b) { return a + b < b; } }"],
    ),
    stated("02", "These are the exceptions", "It introduces the list after it, whose items have their own cases."),
    rule(
        "02",
        "A literal is an instance of a prelude class",
        &[],
        &["class A { Int8 a = 1; Float64 b = 1; String s = \"x\"; Char c = 'c'; Boolean t = true; Int n = \"x\".length() + 'c'.code(); }"],
    ),
    rule("02", "An array is an ordinary object of the prelude class `Array<T>`", &[], &["class A { Array<Int> f(Int[] a) { return a; } Int[] g(Array<Int> a) { return a; } Object h(Int[] a) { return a; } }"]),
    stated("02", "The implementation supplies its storage", "It gives the reason for the exception."),
    stated("02", "also has a rule for default elements that belongs to arrays alone", "It points to chapter 6, where `new T[n]` has its cases."),
    rule("02", "A prelude method may have a body that the implementation supplies", &[("class A { @Intrinsic Int f(); }", "`@Intrinsic` is rejected outside the package `cleat`")], &[]),
    held("02", "It is marked `@Intrinsic`", "spec_tables", "the_prelude_declares_the_annotations_of_section_8_10"),
    stated("02", "hold fixed places in the hierarchy, given in this chapter and in chapter 5", "It points to the sections on `Object`, `Null` and `Enum`, whose sentences have their own cases."),
    stated("02", "The prelude's annotations have rules that the compiler applies", "It points to chapter 8, whose sentences have their own cases."),
    stated("02", "Syntax that is defined by a method or an interface is not an exception", "It introduces the four sentences after it."),
    rule(
        "02",
        "An operator is a method call.",
        &[],
        &["class P { public P plus(P o) { return this; } public P minus(P o) { return this; } public P get(Int i) { return this; } } class A { P f(P a, P b) { return (a + b - a)[0]; } }"],
    ),
    rule(
        "02",
        "`for` works on any `Iterable`",
        &[("class Count { } class A { void f() { for (Int x : new Count()) { } } }", "a `for` statement visits an `Iterable`, and `Count` is not one")],
        &["class Count implements Iterable<Int> { @Override public Iterator<Int> iterator() { return new Upto(); } } class Upto implements Iterator<Int> { Int i = 0; @Override public Boolean hasNext() { return i < 3; } @Override public Int next() { i = i + 1; return i; } } class A { Int f() { var n = 0; for (Int x : new Count()) { n += x; } return n; } }"],
    ),
    rule("02", "`using` works on any class with a `close` method", &[], &["class R { public void close() { } } class A { void f() { using (R r = new R()) { } } }"]),
    rule("02", "A lambda becomes an instance of any interface with one method", &[], &["interface Check { Boolean test(Int n); } class A { Check f() { return (n) -> n > 0; } Boolean g() { return f().test(1); } }"]),
    // ---- 2.3 ----
    rule("02", "A class declared without `value` is a reference class", &[], &["class A { Int n = 0; void f() { n = 1; } }"]),
    ran("02", "each evaluation of `new` creates an instance distinct from every other", RUN, "identity: false false true"),
    ran("02", "The default `equals` of a reference class is identity, and the default `hashCode` agrees with it", RUN, "reference equals: true false true"),
    rule("02", "A class declared with `value` is a value class", &[], &["value class V { public Int a; } class A { V f() { return new V(1); } }"]),
    rule(
        "02",
        "Its fields are final without writing `final`",
        &[("value class V { public Int a; public void set() { a = 2; } }", "the field `a` is not assigned here: a field of a value class is final")],
        &["value class V { public Int a; public final Int b; }"],
    ),
    ran("02", "each pair of corresponding fields is equal under `equals`", RUN, "value equals: true false false true"),
    ran("02", "The default `hashCode` agrees with that comparison", RUN, "value equals: true false false true"),
    ran("02", "Two evaluations of `new` with equal arguments produce equal instances, and nothing distinguishes them", RUN, "value identity: true true"),
    rule("02", "A value class is final.", &[("value class V { public Int a; } class W extends V { }", "`V` is not a class that can be extended")], &[]),
    rule("02", "It may implement interfaces.", &[], &["interface I { Int f(); } value class V implements I { public Int a; @Override public Int f() { return a; } }"]),
    stated("02", "defines construction for both kinds", "It points to chapter 9, whose sentences have their own cases."),
    // ---- 2.4 ----
    rule(
        "02",
        "A class extends one class and implements any number of interfaces",
        &[("open class P { } open class Q { } class C extends P, Q { }", "expected `{`, found `,`")],
        &["open class P { } interface I { } interface J { } class C extends P implements I, J { }"],
    ),
    rule("02", "A class with no `extends` clause extends `Object`", &[], &["class A { } class B { Object f(A a) { return a; } String g(A a) { return a.toString(); } }"]),
    rule("02", "`final` may be written to state that default", &[("final class A { } class B extends A { }", "`A` is final")], &["final class A { }"]),
    rule(
        "02",
        "`open` lets any class that can see the class extend it",
        &[("==== a/P.cleat\npackage a; package open class P { }\n==== b/C.cleat\npackage b; class C extends a.P { }", "`a.P` is not visible here")],
        &["==== a/P.cleat\npackage a; public open class P { }\n==== b/C.cleat\npackage b; class C extends a.P { }"],
    ),
    rule("02", "`abstract` declares a reference class with no instances of its own", &[("abstract class A { } class B { A f() { return new A(); } }", "an abstract class has no instances of its own")], &[]),
    rule("02", "It may declare abstract methods", &[], &["abstract class A { abstract Int f(); Int g() { return f(); } }"]),
    rule(
        "02",
        "Any class that can see it may extend it, unless it is also `sealed`",
        &[("sealed abstract class A permits B { } class B extends A { } class C extends A { }", "`A` is sealed and does not permit this type")],
        &["abstract class A { } class B extends A { }"],
    ),
    // ---- 2.5 ----
    rule("02", "`cleat.Object` is an open reference class", &[], &["class A extends Object { } class B extends cleat.Object { }"]),
    rule("02", "Every class other than `Null` is a subclass of it", &[], &["class A { Object f(String s, Int n, List<Int> xs, Int[] arr, A a) { Object o = s; o = n; o = xs; o = arr; return a; } }"]),
    held("02", "It declares:", "spec_examples", "objects_root_methods"),
    rule(
        "02",
        "The first four declare a `@Nullable` receiver",
        &[("class A { Class f(@Nullable Object o) { return o.getClass(); } }", "`getClass` is sent to a `@Nullable Object`")],
        &["class A { String f(@Nullable Object o) { return o.toString() + o.hashCode() + o.equals(o) + o.identical(o); } }"],
    ),
    stated("02", "says what runs for the three open methods when the receiver is `null`", "It points to chapter 5, whose sentences have their own cases."),
    rule(
        "02",
        "An override of them declares an ordinary receiver",
        &[("class A { @Override public String toString(@Nullable A this) { return \"a\"; } }", "an override of `toString` declares an ordinary receiver")],
        &["class A { @Override public String toString() { return \"a\"; } }"],
    ),
    ran("02", "The default `equals` and `hashCode` are those of", RUN, "reference equals: true false true"),
    ran("02", "The default `toString` of a value class is the simple name of the class", RUN, "toString: Point(1, 2)"),
    ran("02", "A value class `Point` with fields 1 and 2 gives `Point(1, 2)`", RUN, "toString: Point(1, 2)"),
    stated("02", "The default `toString` of a reference class is chosen by the implementation", "It leaves the text to the implementation."),
    rule(
        "02",
        "A class may override `equals`, `hashCode` and `toString`",
        &[],
        &["class A { @Override public Boolean equals(@Nullable Object o) { return o instanceof A; } @Override public Int hashCode() { return 7; } @Override public String toString() { return \"A\"; } }"],
    ),
    stated("02", "The overrides in the prelude meet them", "It is a claim about the prelude's source, which the programs of tests/behavior exercise and no checker decides."),
    ran("02", "asks whether anything could tell `a` from `b`", RUN, "identical: true false false true false false"),
    ran("02", "Two instances of reference classes are identical when they are the same instance", RUN, "identity: false false true"),
    ran("02", "Two instances of a value class are identical when they have the same class", RUN, "value identity: true true"),
    ran("02", "`null` is identical to `null` and to nothing else", RUN, "identical: true false false"),
    ran("02", "two floats are identical when `totalOrder`", RUN, "identical: true false false true false"),
    ran("02", "`identical` is defined for every pair of values", RUN, "identical: true false false true false false"),
    ran("02", "`getClass` returns the class object of the instance's class", RUN, "getClass: true true false"),
    rule("02", "There is no per-object monitor", &[("class A { void f(Object o) { o.wait(); } }", "`Object` has no method named `wait`"), ("class A { void f(Object o) { o.notify(); } }", "`Object` has no method named `notify`")], &[]),
    rule("02", "A lock is a `Lock`, specified in", &[], &["class A { Int n = 0; final Lock lock = new Lock(); void f() { lock.exclusive(() -> { n += 1; }); } }"]),
    // ---- 2.6 ----
    rule("02", "An interface declares methods", &[], &["interface I { Int f(); String g(Int n); }"]),
    rule("02", "A method without a body is abstract", &[("interface I { Int f(); } class C implements I { }", "`C` does not implement `f` of `I`")], &["interface I { Int f(); } abstract class C implements I { }"]),
    rule("02", "A method with a body is a default implementation", &[], &["interface I { Int f() { return 1; } } class C implements I { } class D { Int g(C c) { return c.f(); } }"]),
    ran("02", "A class that implements the interface inherits it and may override it", RUN, "interface body: interface body, class body"),
    rule(
        "02",
        "`final` on a method with a body forbids the override",
        &[("interface I { final Int f() { return 1; } } class C implements I { @Override public Int f() { return 2; } }", "`f` is final in `I` and cannot be overridden")],
        &["interface I { final Int f() { return 1; } } class C implements I { }"],
    ),
    rule(
        "02",
        "Interface methods are public",
        &[("interface I { Int f(); } class C implements I { @Override Int f() { return 1; } }", "an overriding method has the audience of the method it overrides, or a wider one")],
        &["==== a/I.cleat\npackage a; public interface I { Int f(); }\n==== b/B.cleat\npackage b; import a.I; class B { Int g(I i) { return i.f(); } }"],
    ),
    rule(
        "02",
        "A field declared in an interface is `public static final`, whether or not those words are written",
        &[("interface I { Int X = 1; } class A { void f() { I.X = 2; } }", "the static final field `X` is assigned only by its initializer or a static initializer block")],
        &["==== a/I.cleat\npackage a; public interface I { Int X = 1; }\n==== b/B.cleat\npackage b; class B { Int f() { return a.I.X; } }"],
    ),
    rule(
        "02",
        "A class implements any number of interfaces, and an interface extends any number of interfaces",
        &[],
        &["interface I { } interface J { } interface K extends I, J { } class C implements I, J, K { } class D implements K { I f() { return this; } }"],
    ),
    rule("02", "Extension and implementation are nominal", &[("interface I { Int f(); } class C { public Int f() { return 1; } } class D { I g(C c) { return c; } }", "`C` is not assignable to `I`")], &[]),
    ran("02", "A method declared in the class takes precedence over an interface body of the same signature", RUN, "interface body: interface body, class body"),
    rule("02", "An interface that is not sealed may be implemented by any type that can see it", &[], &["open interface J { } interface I { } class C implements I, J { } interface K extends I { }"]),
    rule("02", "A static method with a body belongs to the interface's class object", &[], &["interface I { static Int one() { return 1; } } class A { Int f() { return I.one(); } }"]),
    rule(
        "02",
        "A static method without a body is a requirement on implementers",
        &[("interface Z { static Int zero(); } class C implements Z { }", "`C` does not declare the static method `zero` that `Z` requires"), ("interface Z { static Int zero(); } class C implements Z { @Override static Int zero() { return 0; } }", "an overriding method has the audience of the method it overrides, or a wider one")],
        &["interface Z { static Int zero(); } class C implements Z { @Override public static Int zero() { return 0; } } abstract class D implements Z { }"],
    ),
    rule(
        "02",
        "That method carries `@Override`, as",
        &[("interface Z { static Int zero(); } class C implements Z { public static Int zero() { return 0; } }", "`zero` overrides or implements a method and must carry `@Override`")],
        &["interface Z { static Int zero(); } class C implements Z { @Override public static Int zero() { return 0; } }"],
    ),
    rule(
        "02",
        "The signature may use the interface's type parameters, which stand for the implementer's type arguments",
        &[],
        &["interface Z<T> { static T zero(); } class C implements Z<C> { @Override public static C zero() { return new C(); } }"],
    ),
    rule("02", "so it declares `public static Int zero()`", &[], &["class A { Int f() { return Int.zero(); } Numeric<Int> g(Int n) { return n; } }"]),
    rule("02", "A requirement is called through a type parameter, as", &[], &["class A { static <T extends Numeric<T>> T z() { return T.zero(); } Int g() { return A.<Int>z(); } }"]),
    rule("02", "It is not called on the interface itself", &[("class A { void f() { var z = Numeric.zero(); } }", "`zero` is a static requirement of `Numeric`; it is called through a type parameter, not on the interface")], &[]),
    // ---- 2.7 ----
    rule("02", "A `static` member belongs to its class and not to any instance", &[], &["class C { public static Int n = 1; public static Int f() { return n; } } class A { Int g() { return C.n + C.f(); } }"]),
    ran("02", "A static field is one slot", RUN, "slots: 2 1 3"),
    ran("02", "A static member is selected by the compile-time type that names it and is not dispatched", "Rules", "statics: base derived"),
    ran("02", "A static member of a subclass with the same name and signature hides the superclass's member", "Rules", "statics: base derived"),
    ran("02", "A generic class has one copy of each static member, shared by all of its instantiations", RUN, "generic static: 2"),
    ran("02", "Every class, interface, enum and annotation has a class object, which is an instance of `Class`", RUN, "class objects: t.Greeter t.Planet t.Mark t.Thing"),
    ran("02", "A generic type has a distinct class object for each set of type arguments", RUN, "generic class objects: false true"),
    rule("02", "`C.class` is the class literal", &[], &["class C { } class A { Class f() { return C.class; } }"]),
    rule("02", "Its type is `Class`", &[("class C { } class A { String f() { return C.class; } }", "`Class` is not assignable to `String`")], &["class C { } class A { String f() { Class c = C.class; return c.getName(); } }"]),
    rule(
        "02",
        "For a generic type it is written with type arguments",
        &[("class A { Class f() { return List.class; } }", "`List` is generic and is written with its type arguments")],
        &["class A { Class f() { return List<String>.class; } }"],
    ),
    ran("02", "`getName` returns the qualified name of the class, with its type arguments as chapter 7 writes them", RUN, "generic class objects: false true cleat.List<cleat.String>"),
    ran("02", "asks whether two values have the same class", RUN, "getClass: true true false"),
    rule(
        "02",
        "`Class` also declares the methods of",
        &[],
        &["annotation M; class A { @Nullable M f(Class c) { return c.<M>getAnnotation(); } Field[] g(Class c) { return c.<M>getAnnotatedFields(); } Method[] h(Class c) { return c.<M>getAnnotatedMethods(); } }"],
    ),
    rule("02", "There is no other reflection", &[("class A { void f(Class c) { var m = c.getDeclaredFields(); } }", "`Class` has no method named `getDeclaredFields`")], &[]),
    // ---- 2.8 ----
    ran("02", "A field is a slot of an instance, or of the class object when it is `static`", RUN, "slots: 2 1 3"),
    rule("02", "reads the field by name and assigns it by name", &[], &["class P { public Int x = 1; } class A { Int f(P p) { p.x = 2; p.x += 1; return p.x; } }"]),
    rule("02", "No accessor method stands between them", &[("class P { public Int x = 1; } class A { Int f(P p) { return p.getX(); } }", "`P` has no method named `getX`")], &[]),
    rule(
        "02",
        "A field of a reference class is assignable unless it is declared `final`",
        &[("class P { public final Int x = 1; } class A { void f(P p) { p.x = 2; } }", "the field `x` is not assigned here: it is final")],
        &["class P { public Int x = 1; } class A { void f(P p) { p.x = 2; } }"],
    ),
    rule("02", "A field of a value class is final.", &[("value class V { public Int a; } class A { void f(V v) { v.a = 2; } }", "a field of a value class is final")], &[]),
    ran("02", "A field of a subclass with the same name as a field of a superclass hides it", "Rules", "fields: 1 2 1"),
    ran("02", "The static type of the receiver selects between them", "Rules", "fields: 1 2 1"),
    // ---- 2.9 ----
    held("02", "An enum is declared with the keyword `enum`", "spec_examples", "objects_enums"),
    rule("02", "An enum is a final reference class with a fixed set of instances, its constants", &[("enum E { A } class C extends E { }", "`E` is not a class that can be extended")], &["enum E { A, B } class C { Object f() { return E.A; } }"]),
    rule("02", "The declaration lists the constants first", &[("enum E { Int n = 1; A }", "expected `}`, found `n`")], &["enum E { A; Int n = 1; }"]),
    ran("02", "created before any other static initializer of the enum runs", RUN, "enum statics: 2"),
    ran("02", "A constant may pass arguments to a constructor of the enum", RUN, "enum: VENUS 1 2 MERCURY 1"),
    rule(
        "02",
        "An enum's constructors are private, and no other expression creates an instance of the enum",
        &[("enum E { A; E() { } } class C { E f() { return new E(); } }", "`new E` is rejected: no expression creates an instance of an enum"), ("enum E { A; public E() { } }", "the constructors of an enum are private")],
        &["enum E { A; E() { } }"],
    ),
    rule(
        "02",
        "After its constants, an enum may declare fields, constructors and methods, and it may implement interfaces",
        &[],
        &["interface Named { String label(); } enum E implements Named { A(1), B(2); public final Int n; E(Int n) { this.n = n; } @Override public String label() { return name() + n; } }"],
    ),
    stated("02", "Every enum has these methods", "It introduces the table after it, whose rows have their own cases."),
    ran("02", "The constant's identifier, as a `String`", RUN, "enum: VENUS"),
    ran("02", "The constant's position in the list, counting from zero, as an `Int`", RUN, "enum: VENUS 1"),
    ran("02", "A new array of the constants in source order", RUN, "enum statics: 2 false"),
    ran("02", "The constant with that name", RUN, "enum: VENUS 1 2 MERCURY 1"),
    ran("02", "It raises `IllegalArgumentException` when there is none", RUN, "valueOf raises"),
    ran("02", "`equals` on an enum is identity", RUN, "enum equals: true false true"),
    held("02", "which is the superclass of every enum", "spec_tables", "every_enum_has_the_methods_of_section_2_9"),
    ran("02", "`Enum` exists so that a method can accept any enum", RUN, "enum as Enum: VENUS#1"),
    // ---- 2.10 ----
    stated("02", "A member is selected in two steps", "It introduces the two steps after it."),
    ran("02", "The compile-time types of the receiver and the arguments choose a member", RUN, "dispatch: a circle, String, Object"),
    ran("02", "the method that runs is the one the receiver's class has for that signature at run time", RUN, "dispatch: a circle"),
    rule("02", "`Type.name` selects a static member of that type", &[], &["class C { public static Int n = 1; public static Int f() { return 2; } } class A { Int g() { return C.n + C.f(); } }"]),
    ran("02", "A field hides a superclass field of the same name", "Rules", "fields: 1 2 1"),
    ran("02", "A static method hides a superclass static method of the same signature", "Rules", "statics: base derived"),
];
