//! Chapter 13, Concurrency: the sentences that define and describe.

use super::{held, ran, rule, stated, Rule};

const RUN: &str = "Sentences13";
const EVERY_INTERLEAVING: &str = "It holds for every interleaving, which no run can enumerate.";
const PERMISSION: &str = "It says what an implementation may do, and no run shows that it does not.";

pub const SENTENCES: &[Rule] = &[
    // ---- 13.1 ----
    ran("13", "A program starts with one thread, which runs `main`", RUN, "thread: 7 true false"),
    ran("13", "A thread runs a body to completion", RUN, "thread: 7"),
    ran("13", "Threads share every object they can reach", RUN, "thread: 7"),
    ran("13", "creates a thread that runs `body.invoke()`, and returns once the thread exists", RUN, "alive: true true"),
    rule(
        "13",
        "Its result may be ignored, and so may the result of `fork`",
        &[],
        &["class A { void f() { Thread.start(() -> { }); var z = Scope.call((scope) -> { scope.fork(() -> 1); return 0; }); } }"],
    ),
    rule(
        "13",
        "The body is a lambda, and it captures locals as",
        &[("class A { void f() { var n = 1; n = 2; Thread.start(() -> { var m = n; }); } }", "a lambda may use `n` only if it is never assigned after it is initialized")],
        &["class A { void f(Int k) { var n = k + 1; Thread.start(() -> { var m = n + k; }); } }"],
    ),
    ran("13", "`Thread.current` returns the thread that is running", RUN, "thread: 7 true false"),
    stated("13", "`sleep` waits for at least that many milliseconds", "No program can read a clock, so no run of a program shows how long it waited."),
    ran("13", "A negative argument raises `IllegalArgumentException`", RUN, "sleep: a negative time raises"),
    ran("13", "`join` waits until the thread's body has completed", RUN, "after join: false"),
    ran("13", "Joining the running thread raises `IllegalStateException`", RUN, "join: joining the running thread raises"),
    ran("13", "`isAlive` is `true` from `start` until the body has completed", RUN, "alive: true"),
    ran("13", "An exception that leaves the body ends that thread and no other", RUN, "uncaught: the body failed, and main goes on"),
    held("13", "Its `toString` is written to the host's error stream, and `uncaught` returns it from then on", "behavior", "an_exception_that_leaves_a_thread_is_written_to_the_error_stream"),
    ran("13", "`uncaught` returns `null` for a thread that is running or that completed normally", RUN, "alive: true true"),
    ran("13", "The program ends when `main` returns, as", "Rules", "main returns"),
    ran("13", "A program that needs its threads to finish joins them, or starts them in a scope", RUN, "scope: 5 3"),
    // ---- 13.2 ----
    rule(
        "13",
        "Two threads may read and assign the same field, static field or array element",
        &[],
        &["class Box { public Int n = 0; public static Int shared = 0; } class A { void f(Box b, Int[] a) { Thread.start(() -> { b.n = 1; Box.shared = 2; a[0] = 3; }); Thread.start(() -> { var x = b.n + Box.shared + a[0]; }); } }"],
    ),
    stated("13", "The language guarantees four things about what they see", "It introduces the four guarantees after it."),
    stated("13", "It returns a value that some assignment stored in that location, or the location's initial value", EVERY_INTERLEAVING),
    stated("13", "No constructor and no method ever sees a field that has not been assigned", "It follows from the constructor rules of section 9.5, whose sentences have their own cases."),
    stated("13", "That holds across threads", EVERY_INTERLEAVING),
    stated("13", "Each row of the table below orders everything the first thread did before the first action", "It introduces the table after it, whose rows have their own cases."),
    ran("13", "returns the value of that assignment", RUN, "start and join: 6"),
    stated("13", "When two threads use a location with nothing ordering them", PERMISSION),
    stated("13", "It may be an older value than the latest one", PERMISSION),
    stated("13", "Nothing else goes wrong: the program's types hold, and no other location is affected", EVERY_INTERLEAVING),
    ran("13", "| A thread releases a `Lock` | A thread next acquires that lock |", RUN, "lock: 4000"),
    ran("13", "| An operation on an atomic cell | A later operation on the same cell |", RUN, "atomic steps: 4000"),
    ran("13", "| `Thread.start` or `Scope.fork` | The first action of the new thread's body |", RUN, "start and join: 6"),
    ran("13", "| The last action of a thread's body | The return of `join`, or of `result` on its task |", RUN, "start and join: 6"),
    ran("13", "| The end of a class's initialization | Any thread's use of that class |", RUN, "class: 7 7"),
    stated("13", "Within one thread, actions are ordered as", "It points to section 9.1, whose sentences have their own cases."),
    stated("13", "is a read and a later assignment", "It says how the next sentence comes about."),
    stated("13", "Two threads that run it with nothing ordering them may lose an update", PERMISSION),
    rule("13", "There is no `volatile` modifier and no per-object monitor", &[("class A { volatile Int x = 1; }", "there is no modifier `volatile`"), ("class A { void f(Object o) { o.wait(); } }", "`Object` has no method named `wait`")], &[]),
    // ---- 13.3 ----
    ran("13", "A `Lock` is held by at most one thread at a time", RUN, "lock: 4000"),
    ran("13", "`lock` waits until the running thread can hold it", RUN, "lock: 4000"),
    ran("13", "A thread that holds it may call `lock` again, and it then releases the lock by calling `unlock` as many times", RUN, "reentrant: locked twice, unlocked twice, and then not held"),
    ran("13", "`exclusive` calls `lock`, runs the body, and calls `unlock` however the body completed", RUN, "exclusive: 42 1"),
    ran("13", "It returns the body's result", RUN, "exclusive: 42"),
    ran("13", "A `Condition` belongs to the lock whose `newCondition` created it", RUN, "condition without its lock: 3"),
    ran("13", "Each of its three methods raises `IllegalStateException` unless the running thread holds that lock", RUN, "condition without its lock: 3"),
    ran("13", "`await` releases the lock completely, waits, and holds the lock again as before when it returns", RUN, "signal: 4"),
    stated("13", "It may return without a signal, so a caller tests what it waits for in a loop", PERMISSION),
    ran("13", "`signal` lets one waiting thread return from `await`, if there is one", RUN, "signal: 4"),
    ran("13", "`signalAll` lets every waiting thread return", RUN, "signalAll: 3"),
    // ---- 13.4 ----
    ran("13", "An atomic cell holds one value", RUN, "atomic int: 5"),
    ran("13", "Each method is one step", RUN, "atomic steps: 4000"),
    ran("13", "`compareAndSet` stores `update` when the cell holds `expected`, and returns whether it did", RUN, "atomic int: 5 true false 6"),
    ran("13", "`AtomicInt` compares with `equals`", RUN, "atomic int: 5 true false 6"),
    ran("13", "so a cell of a reference class compares references", RUN, "atomic cell: false true true true 2"),
    ran("13", "`addAndGet` adds `delta` to the cell and returns the sum", RUN, "atomic int: 5 true false 6 16"),
    ran("13", "`incrementAndGet` is `addAndGet(1)`", RUN, "atomic int: 5 true false 6 16 17"),
    ran("13", "the method raises `ArithmeticException` and the cell is unchanged", RUN, "overflow: raises, and the cell is unchanged true"),
    // ---- 13.5 ----
    ran("13", "A scope starts tasks and waits for all of them", RUN, "scope: 5 3"),
    ran("13", "No task outlives the call that created its scope", RUN, "scope: 5 3"),
    ran("13", "runs `body` on the running thread with that scope, and returns the body's result", RUN, "scope: 5"),
    ran("13", "it cancels the scope if the body raised an exception, and it waits for every task of the scope to complete", RUN, "body: raises the body failed, its task was cancelled 1"),
    ran("13", "`fork` starts a task: a new thread that runs `body.invoke()`", RUN, "fork: returned before the task ended, result 1, done true, on the main thread false"),
    ran("13", "It returns once the thread exists", RUN, "fork: returned before the task ended"),
    ran("13", "Any other `fork` raises `IllegalStateException`", "Rules", "fork from another thread raises"),
    ran("13", "`result` waits until the task has completed, and returns what its body returned", RUN, "fork: returned before the task ended, result 1"),
    ran("13", "If the body raised an exception, `result` raises that exception", RUN, "result: raises the task failed"),
    ran("13", "`isDone` is `true` once the body has completed in either way", RUN, "result: raises the task failed, done true"),
    ran("13", "A task fails when its body raises an exception other than `CancellationException`", RUN, "body: raises the body failed, its task was cancelled 1, suppressed 0"),
    ran("13", "A task that fails cancels its scope.", RUN, "a failed task cancels its scope: true"),
    stated("13", "it completes in the first of these ways that applies", "It introduces the three ways after it, which have their own cases."),
    ran("13", "If the body of `call` raised an exception, that exception propagates", RUN, "body: raises the body failed"),
    ran("13", "The exceptions of failed tasks are recorded as suppressed on it", RUN, "body: raises the body failed, its task was cancelled 1, suppressed 0"),
    ran("13", "the exception of the first failed task in fork order propagates, with those of the others suppressed on it", RUN, "failure: first in fork order, suppressed 1: second in fork order"),
    ran("13", "Otherwise `call` returns the body's result", RUN, "scope: 5"),
    // ---- 13.6 ----
    ran("13", "Cancellation is a request", RUN, "cancel: true true, and the task ran on"),
    ran("13", "A cancelled task goes on running until it reaches a point that checks for the request", RUN, "cancel: true true, and the task ran on"),
    ran("13", "`cancel` marks the scope as cancelled, and `isCancelled` reports the mark", RUN, "cancel: true"),
    ran("13", "A scope is also cancelled by a task that fails and by an exception from the body of its `call`", RUN, "a failed task cancels its scope: true"),
    ran("13", "A scope that is cancelled stays cancelled", RUN, "cancel: true true"),
    ran("13", "A task is cancelled when its scope is", RUN, "points: raised"),
    held("13", "A cancelled task raises `CancellationException` at these points, and at no others", "spec_rules", "cancellation_is_raised_only_where_section_13_6_says"),
    ran("13", "a call of `Thread.checkCancelled`;", RUN, "points: raised"),
    ran("13", "when it is called and while it waits", RUN, "points: raised raised raised raised raised"),
    ran("13", "`Lock.lock` is not such a point, so code that cleans up may take a lock", RUN, "lock is not a point: returned"),
    held("13", "A task inside a foreign call finishes the call", "spec_rules", "cancellation_is_raised_only_where_section_13_6_says"),
    stated("13", "A long computation in a task calls `Thread.checkCancelled` now and then", "It is advice to a program."),
];
