//! Chapter 1, Source: the sentences that define and describe.

use super::{held, ran, rule, stated, Rule};

pub const SENTENCES: &[Rule] = &[
    // ---- 1.1 ----
    stated("01", "Other examples illustrate a rule", "It says how to read the examples."),
    stated("01", "Where an example lists the members of a prelude class", "It says how to read the examples, and tests/spec_examples.rs reads such an example as signatures."),
    held("01", "[Chapter 11](11-syntax.md) gives the grammar", "spec_tables", "every_program_the_grammar_must_derive_is_parsed"),
    stated("01", "The other chapters describe syntax in prose and by example", "It says how the document is arranged."),
    // ---- 1.2 ----
    rule("01", "A compilation unit is a UTF-8 file whose name ends in `.cleat`", &[], &["class A { String s = \"\u{e9}\u{6f22}\u{1F600}\"; }"]),
    rule("01", "Whitespace is U+0009, U+000A, U+000B, U+000C, U+000D and U+0020", &[], &["class\tA\u{000B}{\u{000C}Int\r\nx = 1 ; }"]),
    rule(
        "01",
        "Whitespace separates tokens and is otherwise ignored",
        &[("classA { }", "expected a class, an interface, an enum or an annotation, found `classA`")],
        &["class A{Int x=1;Int f(){return x+1;}}", "class   A   {   Int   x   =   1   ;   }"],
    ),
    rule("01", "A comment is `//` through the end of the line, or `/*` through the next `*/`", &[], &["class A { // a note }\n Int x = 1; /* more\n notes */ Int y = 2; }"]),
    rule("01", "A comment separates tokens as whitespace does", &[], &["class/* c */A { Int/**/x = 1; }"]),
    // ---- 1.3 ----
    rule(
        "01",
        "The longest token that can be read at each point is the one read",
        &[],
        &["class A { Int f(Int a, Int b) { return a+++b; } Boolean g(Int a, Int b) { return a<=b; } Int h(Int a) { a<<=1; return a; } }"],
    ),
    rule("01", "is always read as a single character where a type argument list is being closed", &[], &["class A { List<List<Int>> x = new List<List<Int>>(); Int f(Int a) { return a >> 1; } }"]),
    rule(
        "01",
        "An identifier is a character in Unicode category L, or `_` or `$`",
        &[("class A { Int 9a = 1; }", "a numeric literal has no suffix and is not followed by a letter"), ("class A { Int a-b = 1; }", "expected `;`, found `-`")],
        &["class A { Int _a = 1; Int $b = 2; Int \u{e9}1 = 3; Int \u{540d}\u{524d} = 4; Int a_$9 = 5; }"],
    ),
    held("01", "These words are keywords.", "spec_tables", "the_keywords_of_section_1_3_are_the_lexers"),
    rule("01", "A keyword is not an identifier", &[("class A { Int while = 1; }", "`while` is a keyword and cannot be a name"), ("class A { void new() { } }", "`new` is a keyword and cannot be a name")], &[]),
    rule("01", "A method may be named `open`, and a field `value`", &[], &["class A { Int value = 1; Int open() { return value; } }"]),
    rule(
        "01",
        "Among the modifiers of a type, a method or a constructor",
        &[],
        &["open class A { open void f() { } } sealed interface S permits P { } class P implements S { } class F { foreign static void g(); Int foreign = 1; Int sealed = 2; }"],
    ),
    rule("01", "Directly before `class`", &[], &["value class V { public Int a; } class A { Int value = 1; }"]),
    rule("01", "Where a type declaration may begin, after its modifiers", &[], &["annotation M; class A { Int annotation = 1; }"]),
    rule("01", "After the header of a class or an interface, before its `{`", &[], &["sealed class A permits B { Int permits = 1; } class B extends A { }"]),
    rule("01", "in the type parameter list of a class or an interface", &[], &["interface F<in A, out B> { B apply(A in); } class C { Int out = 1; Int in = 2; }"]),
    rule("01", "Where a switch arm may begin", &[], &["class A { Int default = 1; Int f(Int n) { return switch (n) { case 1 -> 1; default -> default; }; } }"]),
    rule("01", "Directly after an audience keyword, before `(`", &[], &["class A { public only(B) Int x = 1; Int only = 2; } class B { }"]),
    rule(
        "01",
        "These words are reserved",
        &[
            ("class A { Int boolean = 1; }", "`boolean` is a reserved word"),
            ("class A { Int byte = 1; }", "`byte` is a reserved word"),
            ("class A { Int char = 1; }", "`char` is a reserved word"),
            ("class A { Int double = 1; }", "`double` is a reserved word"),
            ("class A { Int float = 1; }", "`float` is a reserved word"),
            ("class A { Int inline = 1; }", "`inline` is a reserved word"),
            ("class A { Int int = 1; }", "`int` is a reserved word"),
            ("class A { Int long = 1; }", "`long` is a reserved word"),
            ("class A { Int short = 1; }", "`short` is a reserved word"),
            ("class A { Int when = 1; }", "`when` is a reserved word"),
        ],
        &[],
    ),
    rule(
        "01",
        "`true`, `false` and `null` are literals and not identifiers",
        &[("class A { Int null = 1; }", "`null` is a keyword and cannot be a name"), ("class A { Int false = 1; }", "`false` is a keyword and cannot be a name")],
        &["class A { Boolean t = true; Boolean f = false; @Nullable Object n = null; }"],
    ),
    rule(
        "01",
        "An integer literal is a decimal numeral, a hexadecimal numeral introduced by `0x` or `0X`",
        &[("class A { Int a = 0xG; }", "a number needs at least one digit here"), ("class A { Int a = 0b2; }", "a number needs at least one digit here")],
        &["class A { Int a = 10; Int b = 0x1F; Int c = 0X1f; Int d = 0b101; Int e = 0B11; }"],
    ),
    rule(
        "01",
        "A decimal literal is a decimal numeral, `.`, a run of decimal digits, and an optional exponent",
        &[("class A { Rational a = .5; }", "expected an expression, found `.`")],
        &["class A { Rational a = 1.5; Rational b = 1.5e3; Rational c = 2e3; Rational d = 0.25E-2; }"],
    ),
    rule("01", "An exponent is `e` or `E`, an optional `+` or `-`, and a run of decimal digits", &[("class A { Rational a = 1e; }", "a numeric literal has no suffix and is not followed by a letter")], &["class A { Rational a = 1e2; Rational b = 1E+2; Rational c = 1e-2; }"]),
    rule("01", "`_` may be written between two digits", &[("class A { Int a = 1_; }", "`_` in a number stands between two digits"), ("class A { Int a = 1__0; }", "`_` in a number stands between two digits")], &["class A { Int a = 1_000_000; Int b = 0xFF_FF; Rational c = 1_0.2_5; }"]),
    rule(
        "01",
        "Each literal denotes its exact mathematical value",
        &[],
        &["class A { Rational a = 0.1; UInt64 b = 18446744073709551615; Rational c = 123456789012345678901234567890; Rational d = 1e400; }"],
    ),
    rule(
        "01",
        "A character literal is one scalar between `'` marks, written directly or as an escape",
        &[("class A { Char a = 'ab'; }", "a character literal holds exactly one scalar"), ("class A { Char a = ''; }", "a character literal holds exactly one scalar")],
        &["class A { Char a = 'x'; Char b = '\\n'; Char c = '\\u{1F600}'; Char d = '\u{e9}'; }"],
    ),
    rule(
        "01",
        "A string literal is any number of scalars between `\"` marks, on one line",
        &[("class A { String a = \"x\ny\"; }", "this string literal is never closed")],
        &["class A { String a = \"\"; String b = \"h\u{e9}llo \\t\"; }"],
    ),
    stated("01", "The escapes are:", "It introduces the table after it, whose rows have their own cases."),
    ran("01", "U+000A, U+0009, U+000D", "Sentences01", "escapes: 10 9 13"),
    ran("01", "The character after the backslash", "Sentences01", "after the backslash: 92 34 39"),
    ran("01", "`\\u` and four hexadecimal digits", "Sentences01", "four digits: 233 A"),
    ran("01", "one to six hexadecimal digits", "Sentences01", "braces: 128512 65"),
    ran("01", "A text block is a string literal that spans lines", "Sentences01", "text block: true"),
    rule(
        "01",
        "and the end of that line, and it closes with",
        &[("class A { String s = \"\"\"abc\n    \"\"\"; }", "a text block opens with `\"\"\"` and the end of the line")],
        &["class A { String s = \"\"\"\n    abc\n    \"\"\"; }"],
    ),
    ran("01", "on its line is the indent", "Sentences01", "indent: true"),
    ran("01", "Each line break in the content is U+000A", "Sentences01", "line breaks: 14 10"),
    ran("01", "Escapes apply after the indent is removed", "Sentences01", "escaped block: true"),
    rule(
        "01",
        "The separators are",
        &[],
        &["annotation M; class A { @M Int[] a = new Int[] { 1, 2 }; Function1<Int, String> f = Int::toString; Function0<Int> g() { return () -> a[0]; } static Int sum(Int... xs) { return xs.length(); } Int h() { return sum(1, 2, 3); } }"],
    ),
    rule(
        "01",
        "and the compound assignments",
        &[],
        &["class A { Int f(Boolean b, @Nullable Int n, Int m) { m += 1; m -= 1; m *= 2; m %= 3; m &= 1; m |= 2; m ^= 3; m <<= 1; m >>= 1; var k = b ? m : n ?? 0; return k; } }"],
    ),
    // ---- 1.4 ----
    rule(
        "01",
        "A compilation unit has an optional package declaration, then its imports, then its type declarations",
        &[("==== A.cleat\nclass A { } import b.B;\n==== b/B.cleat\npackage b; public class B { }", "expected a class, an interface, an enum or an annotation, found `import`"), ("==== a/A.cleat\nimport b.B; package a; class A { }\n==== b/B.cleat\npackage b; public class B { }", "expected a class, an interface, an enum or an annotation, found `a`")],
        &["==== a/A.cleat\npackage a; import b.B; class A { void f(B x) { } }\n==== b/B.cleat\npackage b; public class B { }", "class A { }"],
    ),
    rule("01", "A type declaration declares a class, an interface, an enum or an annotation", &[], &["class A { } interface I { } enum E { X } annotation M;"]),
    rule(
        "01",
        "names the package of every type the file declares",
        &[],
        &["==== a/b/A.cleat\npackage a.b; public class A { } package class Helper { }\n==== a/b/C.cleat\npackage a.b; class C { void f(Helper h, a.b.A x, a.b.Helper y) { } }"],
    ),
    rule(
        "01",
        "A file declares at most one `public` type, and its name is then the file's name without `.cleat`",
        &[("==== A.cleat\npublic class A { } public class B { }", "a file declares at most one public type"), ("==== A.cleat\npublic class B { }", "the public type `B` must be in a file named `B.cleat`")],
        &["==== A.cleat\npublic class A { } class B { }"],
    ),
    rule("01", "A file may declare no public type", &[], &["==== anything.cleat\nclass A { } class B { }"]),
    rule(
        "01",
        "A type is not declared inside another type, inside a method, or without a name",
        &[
            ("class A { class B { } }", "a type is not declared inside another type"),
            ("class A { void f() { class B { } } }", "a type is not declared inside a method"),
            ("class { }", "expected a name, found `{`"),
            ("class A { Object f() { return new Object() { }; } }", "expected `;`, found `{`"),
        ],
        &[],
    ),
    rule("01", "The package `cleat` is the prelude", &[], &["class A { cleat.List<Int> xs = new cleat.List<Int>(); cleat.Int n = 1; }"]),
    rule(
        "01",
        "Its public types are in scope in every compilation unit without an import",
        &[],
        &["==== a/A.cleat\npackage a; class A { List<Int> xs = new List<Int>(); Map<String, Int> m = new Map<String, Int>(); }"],
    ),
    stated("01", "This specification defines the prelude types that the language depends on", "It says what the document covers."),
    rule(
        "01",
        "The prelude declares further classes in ordinary source",
        &[],
        &["class A { void f() { var a = new List<Int>(); var b = new Map<String, Int>(); var c = new StringBuilder(); Console.println(\"x\"); var t = File.readText(\"x\"); } }"],
    ),
    // ---- 1.5 ----
    rule(
        "01",
        "A package is a namespace for types and for other packages",
        &[],
        &["==== a/X.cleat\npackage a; public class X { }\n==== a/b/Y.cleat\npackage a.b; public class Y { }\n==== C.cleat\nclass C { void f(a.X x, a.b.Y y) { } }"],
    ),
    rule("01", "names the type `C` of the package `a.b`", &[], &["==== a/b/C.cleat\npackage a.b; public class C { }\n==== D.cleat\nclass D { a.b.C f(a.b.C c) { return c; } }"]),
    stated("01", "A package's name says where it sits", "It introduces the sentence after it."),
    rule("01", "whether or not any file declares `package a;`", &[], &["==== a/b/Y.cleat\npackage a.b; public class Y { }\n==== C.cleat\nimport a.b.Y; class C { void f(Y y, a.b.Y z) { } }"]),
    rule(
        "01",
        "Being inside another package gives no access to it",
        &[("==== a/P.cleat\npackage a; package class P { }\n==== a/b/Q.cleat\npackage a.b; class Q { void f(a.P p) { } }", "`a.P` is not visible here")],
        &["==== a/P.cleat\npackage a; public class P { }\n==== a/b/Q.cleat\npackage a.b; class Q { void f(a.P p) { } }"],
    ),
    rule(
        "01",
        "treats every package separately",
        &[("==== a/b/P.cleat\npackage a.b; package class P { }\n==== a/Q.cleat\npackage a; class Q { void f(a.b.P p) { } }", "`a.b.P` is not visible here")],
        &[],
    ),
    // ---- 1.6 ----
    rule("01", "lets the file write `C` for the type `a.b.C`", &[], &["==== a/b/C.cleat\npackage a.b; public class C { }\n==== D.cleat\nimport a.b.C; class D { C f(C c) { return c; } }"]),
    rule(
        "01",
        "does the same for every public type of the package `a.b`",
        &[("==== a/b/P.cleat\npackage a.b; package class P { }\n==== D.cleat\nimport a.b.*; class D { void f(P p) { } }", "there is no type named `P` here")],
        &["==== a/b/C.cleat\npackage a.b; public class C { }\n==== a/b/E.cleat\npackage a.b; public class E { }\n==== D.cleat\nimport a.b.*; class D { void f(C c, E e) { } }"],
    ),
    stated("01", "A simple name used as a type is looked up in this order", "It introduces the list after it, whose lines have their own cases."),
    rule("01", "a type parameter in scope;", &[], &["class Box { } class A<Box> { Int f(Box b) { return 1; } Int g(A<String> a) { return a.f(\"s\"); } }"]),
    rule("01", "a type declared in the same file;", &[], &["class List { public Int only() { return 1; } } class A { Int f(List l) { return l.only(); } }"]),
    rule(
        "01",
        "a type imported by name;",
        &[],
        &["==== p/X.cleat\npackage p; public class X { public Int fromP() { return 1; } }\n==== q/X.cleat\npackage q; public class X { public Int fromQ() { return 2; } }\n==== q/A.cleat\npackage q; import p.X; class A { Int f(X x) { return x.fromP(); } }"],
    ),
    rule(
        "01",
        "a type of the same package;",
        &[],
        &["==== p/X.cleat\npackage p; public class X { public Int fromP() { return 1; } }\n==== q/X.cleat\npackage q; public class X { public Int fromQ() { return 2; } }\n==== q/A.cleat\npackage q; import p.*; class A { Int f(X x) { return x.fromQ(); } }"],
    ),
    rule(
        "01",
        "a type imported by `*`;",
        &[],
        &["==== p/List.cleat\npackage p; public class List { public Int fromP() { return 1; } }\n==== A.cleat\nimport p.*; class A { Int f(List x) { return x.fromP(); } }"],
    ),
    rule("01", "a type of the prelude.", &[], &["class A { Int f(List<Int> x) { return x.size(); } }"]),
    // ---- 1.7 ----
    rule("01", "A field and a method may.", &[], &["class A { Int n = 1; Int n() { return n; } Int twice() { return n + n(); } }"]),
    rule("01", "Two methods may share a name when", &[], &["class A { Int f(Int n) { return n; } Int f(String s) { return 1; } Int f(Int a, Int b) { return a; } }"]),
    rule("01", "An enum constant is a field", &[], &["enum E { A, B } class C { E f() { E first = E.A; return first; } }"]),
    rule("01", "A type name, a member name and a variable name are any identifiers", &[], &["class a { Int B = 1; Int C() { var D = B; return D; } }"]),
    // ---- 1.8 ----
    rule(
        "01",
        "Throughout the body",
        &[],
        &["class A { Int n; public A(Int p) { this.n = p; } Int f(Int p) { { return p; } } Function1<Int, Int> g() { return (p) -> { return p; }; } }"],
    ),
    rule(
        "01",
        "From the end of its declaration to the end of the innermost block around it",
        &[
            ("class A { Int f() { var y = x; var x = 1; return y; } }", "`x` is not a variable or a field in scope"),
            ("class A { Int f() { { var x = 1; } return x; } }", "`x` is not a variable or a field in scope"),
            ("class A { Int f() { var x = x + 1; return x; } }", "`x` is not a variable or a field in scope"),
        ],
        &["class A { Int f() { var x = 1; { var y = x; x = y + 1; } return x; } }"],
    ),
    rule(
        "01",
        "In the condition, the update and the body",
        &[("class A { Int f() { for (var i = 0; i < 3; i++) { } return i; } }", "`i` is not a variable or a field in scope")],
        &["class A { Int f() { var n = 0; for (var i = 0; i < 3; i++) { n += i; } return n; } }"],
    ),
    rule(
        "01",
        "The variable of a `for` over a collection",
        &[("class A { Int f(List<Int> xs) { for (Int x : xs) { } return x; } }", "`x` is not a variable or a field in scope")],
        &["class A { Int f(List<Int> xs) { var n = 0; for (Int x : xs) { n += x; } return n; } }"],
    ),
    rule(
        "01",
        "In the `catch` block",
        &[("class A { String f() { try { } catch (Throwable e) { } return e.message(); } }", "`e` is not a variable, a field or a type in scope")],
        &["class A { String f() { try { } catch (Throwable e) { return e.message(); } return \"\"; } }"],
    ),
    rule(
        "01",
        "In the later bindings and in the block",
        &[("class R { public R() { } public void close() { } } class A { R f() { using (R a = new R()) { } return a; } }", "`a` is not a variable or a field in scope")],
        &["class R { public R() { } public R(R other) { } public void close() { } } class A { void f() { using (R a = new R(), R b = new R(a)) { var c = a; var d = b; } } }"],
    ),
    rule(
        "01",
        "In that arm's body",
        &[("class A { Int f(Object o) { switch (o) { case String s -> { return s.length(); } case Int n -> { return s.length(); } default -> { return 0; } } } }", "`s` is not a variable, a field or a type in scope")],
        &["class A { Int f(Object o) { switch (o) { case String s -> { return s.length(); } case Int n -> { return n; } default -> { return 0; } } } }"],
    ),
    rule("01", "In the statement it labels", &[("class A { void f() { a: while (true) { break; } while (true) { break a; } } }", "no statement labeled `a` encloses this `break`")], &["class A { void f() { a: while (true) { while (true) { break a; } } } }"]),
    stated("01", "| A type parameter | As", "It points to section 7.1, whose sentences have their own cases."),
    rule("01", "A variable may have the name of a field", &[], &["class A { Int n = 1; static Int m = 2; Int f(Int n, Int m) { return n + this.n + m + A.m; } }"]),
    rule("01", "A field initializer may name a field declared earlier in the type", &[], &["class A { Int a = 1; Int b = a + 1; static Int c = 2; static Int d = c + 1; }"]),
    rule(
        "01",
        "A simple name is looked up as a variable in scope, then as a field of the enclosing type",
        &[],
        &["open class P { public Int inherited = 1; } class A extends P { Int own = 2; Int f(Int local) { var made = Array.build(1, (i) -> i); return local + own + inherited + made[0]; } }"],
    ),
    rule(
        "01",
        "`a.b` is resolved from the left",
        &[],
        &["==== p/Q.cleat\npackage p; public class Q { public static Q one = new Q(); public Int n = 1; }\n==== A.cleat\nclass A { Int f() { return p.Q.one.n; } }"],
    ),
    rule("01", "When `a` is a variable or a field, `b` is a member of its value", &[], &["class P { public Int n = 1; } class A { P p = new P(); Int f(P q) { return q.n + p.n; } }"]),
    rule(
        "01",
        "When `a` is a type, `b` is a static member",
        &[("class P { public Int n = 1; } class A { Int f() { return P.n; } }", "`n` is an instance field and is read from a value")],
        &["class P { public static Int n = 1; public static Int g() { return n; } } class A { Int f() { return P.n + P.g(); } }"],
    ),
    rule(
        "01",
        "When `a` is a package, `b` is a type or a package inside it",
        &[],
        &["==== p/Q.cleat\npackage p; public class Q { }\n==== p/r/S.cleat\npackage p.r; public class S { }\n==== A.cleat\nclass A { void f(p.Q q, p.r.S s) { } }"],
    ),
    rule(
        "01",
        "A name that could be either a variable or a type is the variable",
        &[],
        &[
            "class P { public static Int n = 1; public Int m = 2; } class A { Int f(P P) { return P.m; } }",
            "==== p/Q.cleat\npackage p; public class Q { }\n==== A.cleat\nclass p { public static Int n = 1; } class A { Int f() { return p.n; } }",
        ],
    ),
];

