"""Writes the prelude's numeric classes. They differ only in name, range and which
conversions are implicit, so they are generated from one description.

Run from the repository root: python compiler/tools/gen_numbers.py
"""
import io

SIGNED = [("Int8", 8), ("Int16", 16), ("Int32", 32), ("Int", 64)]
UNSIGNED = [("UInt8", 8), ("UInt16", 16), ("UInt32", 32), ("UInt64", 64)]
FLOATS = ["Float32", "Float64"]
ALL = [n for n, _ in SIGNED] + [n for n, _ in UNSIGNED] + FLOATS + ["Rational"]


def int_range(name):
    for n, bits in SIGNED:
        if n == name:
            return (-(1 << (bits - 1)), (1 << (bits - 1)) - 1)
    for n, bits in UNSIGNED:
        if n == name:
            return (0, (1 << bits) - 1)
    return None


def implicit(src, dst):
    """Section 6.7: integer to a wider integer, Float32 to Float64, integer to Rational."""
    if src == dst:
        return False
    s, d = int_range(src), int_range(dst)
    if s and d:
        return d[0] <= s[0] and s[1] <= d[1]
    if s and dst == "Rational":
        return True
    return src == "Float32" and dst == "Float64"


def froms(name):
    out = []
    for src in ALL:
        mark = "@Implicit\n    " if implicit(src, name) else ""
        out.append(f"    {mark}@Intrinsic\n    public static {name} from({src} value);\n")
    return "\n".join(out)


HEADER = "// Generated by compiler/tools/gen_numbers.py. Edit the generator, not this file.\npackage cleat;\n\n"

ORDERED = """    @Override
    @Intrinsic
    public Boolean lessThan({n} other);

    @Override
    @Intrinsic
    public Boolean atMost({n} other);

    @Override
    @Intrinsic
    public Boolean greaterThan({n} other);

    @Override
    @Intrinsic
    public Boolean atLeast({n} other);

    @Override
    @Intrinsic
    public Int compare({n} other);
"""

NUMERIC = """    @Override
    @Intrinsic
    public {n} plus({n} other);

    @Override
    @Intrinsic
    public {n} minus({n} other);

    @Override
    @Intrinsic
    public {n} times({n} other);

    @Override
    @Intrinsic
    public {n} negate();

    @Override
    @Intrinsic
    public static {n} zero();

    @Override
    @Intrinsic
    public static {n} one();
"""

INTEGER = """
    @Intrinsic
    public {n} floorDiv({n} other);

    @Intrinsic
    public {n} mod({n} other);

    @Intrinsic
    public {n} truncatingDiv({n} other);

    @Intrinsic
    public {n} truncatingRem({n} other);

    @Intrinsic
    public {n} wrappingPlus({n} other);

    @Intrinsic
    public {n} wrappingMinus({n} other);

    @Intrinsic
    public {n} wrappingTimes({n} other);

    @Intrinsic
    public {n} and({n} other);

    @Intrinsic
    public {n} or({n} other);

    @Intrinsic
    public {n} xor({n} other);

    @Intrinsic
    public {n} complement();

    @Intrinsic
    public {n} shiftLeft(Int count);

    @Intrinsic
    public {n} shiftRight(Int count);

    public {n} min({n} other) {{
        return this < other ? this : other;
    }}

    public {n} max({n} other) {{
        return this > other ? this : other;
    }}

    // The text of an integer in decimal, or null when the text is not one or is out of range.
    @Intrinsic
    public static @Nullable {n} parse(String text);
"""

FLOAT = """
    @Override
    @Intrinsic
    public {n} div({n} other);

    @Intrinsic
    public Int totalOrder({n} other);

    @Intrinsic
    public {n} floor();

    @Intrinsic
    public {n} ceil();

    @Intrinsic
    public {n} truncate();

    @Intrinsic
    public {n} round();

    @Intrinsic
    public {n} sqrt();

    @Intrinsic
    public {n} abs();

    @Intrinsic
    public Boolean isNaN();

    @Intrinsic
    public Boolean isInfinite();

    public {n} min({n} other) {{
        return this < other ? this : other;
    }}

    public {n} max({n} other) {{
        return this > other ? this : other;
    }}

    // The decimal digits of the value rounded to `places` digits after the point.
    @Intrinsic
    public String toFixed(Int places);

    @Intrinsic
    public static @Nullable {n} parse(String text);
"""

RATIONAL = """
    @Override
    @Intrinsic
    public Rational div(Rational other);

    @Intrinsic
    public Boolean isInteger();

    @Intrinsic
    public Rational numerator();

    @Intrinsic
    public Rational denominator();

    @Intrinsic
    public Rational floor();

    @Intrinsic
    public Rational ceil();

    @Intrinsic
    public Rational truncate();

    @Intrinsic
    public Rational round();

    @Intrinsic
    public Rational round(Int places);

    @Intrinsic
    public Rational floorDiv(Rational other);

    @Intrinsic
    public Rational mod(Rational other);

    @Intrinsic
    public Rational abs();

    public Rational min(Rational other) {
        return this < other ? this : other;
    }

    public Rational max(Rational other) {
        return this > other ? this : other;
    }

    // The digits of round(places), with exactly `places` digits after the point.
    @Intrinsic
    public String toDecimal(Int places);

    // A decimal numeral or a fraction "a/b", or null when the text is neither.
    @Intrinsic
    public static @Nullable Rational parse(String text);
"""


def nearest(name):
    return "\n".join(
        f"    @Intrinsic\n    public static {name} nearest({src} value);\n" for src in ALL
    )


def write(name, body):
    io.open(f"prelude/{name}.cleat", "w", encoding="utf-8", newline="\n").write(HEADER + body)


for name, _ in SIGNED + UNSIGNED:
    write(
        name,
        f"public value class {name} implements Numeric<{name}>, Ordered<{name}> {{\n"
        f"    private {name} {{\n    }}\n\n"
        + NUMERIC.format(n=name)
        + "\n"
        + ORDERED.format(n=name)
        + INTEGER.format(n=name)
        + "\n"
        + froms(name)
        + "}\n",
    )

for name in FLOATS:
    write(
        name,
        f"public value class {name} implements Divisible<{name}>, Ordered<{name}> {{\n"
        f"    private {name} {{\n    }}\n\n"
        + NUMERIC.format(n=name)
        + "\n"
        + ORDERED.format(n=name)
        + FLOAT.format(n=name)
        + "\n"
        + froms(name)
        + "\n"
        + nearest(name)
        + "}\n",
    )

write(
    "Rational",
    "public value class Rational implements Divisible<Rational>, Ordered<Rational> {\n"
    "    private Rational {\n    }\n\n"
    + NUMERIC.format(n="Rational")
    + "\n"
    + ORDERED.format(n="Rational")
    + RATIONAL
    + "\n"
    + froms("Rational")
    + "}\n",
)
