"""Writes the prelude's numeric classes. They differ only in name, range and which
conversions are implicit, so they are generated from one description.

A method is `@Intrinsic` only when it is one machine operation, or needs arithmetic the
language has no words for yet. Everything else is written in the language:

- `Int` and `UInt64` have the machine's arithmetic, comparison, bit operations and
  conversions. Their other methods are written over those.
- The narrower integer classes have no arithmetic of their own. Each computes in `Int`
  and converts back, and the conversion raises when the result does not fit.
- The float classes have IEEE 754 arithmetic, rounding, and their conversions.
- `Rational` has exact arithmetic on integers of any size.

Run from the repository root: python compiler/tools/gen_numbers.py
"""
import io

SIGNED = [("Int8", 8), ("Int16", 16), ("Int32", 32), ("Int", 64)]
UNSIGNED = [("UInt8", 8), ("UInt16", 16), ("UInt32", 32), ("UInt64", 64)]
FLOATS = ["Float32", "Float64"]
INTEGERS = [n for n, _ in SIGNED + UNSIGNED]
NARROW = [n for n, bits in SIGNED + UNSIGNED if bits < 64]
ALL = INTEGERS + FLOATS + ["Rational"]


def int_range(name):
    for n, bits in SIGNED:
        if n == name:
            return (-(1 << (bits - 1)), (1 << (bits - 1)) - 1)
    for n, bits in UNSIGNED:
        if n == name:
            return (0, (1 << bits) - 1)
    return None


def width(name):
    return dict(SIGNED + UNSIGNED)[name]


def implicit(src, dst):
    """Section 6.7: integer to a wider integer, Float32 to Float64, integer to Rational."""
    if src == dst:
        return False
    s, d = int_range(src), int_range(dst)
    if s and d:
        return d[0] <= s[0] and s[1] <= d[1]
    if s and dst == "Rational":
        return True
    return src == "Float32" and dst == "Float64"


def conversion(name, src, method, machine):
    """One overload of `from` or `nearest`. `machine` lists the sources the class
    converts by itself. Every other source goes through one of them."""
    mark = "@Implicit\n    " if method == "from" and implicit(src, name) else ""
    head = f"public static {name} {method}({src} value)"
    if src == name:
        return f"    {mark}{head} {{\n        return value;\n    }}\n"
    if src in machine:
        return f"    {mark}@Intrinsic\n    {head};\n"
    if src == "Float32":
        # Every Float32 is a Float64, so nothing is lost on the way.
        via = "Float64.from(value)"
    else:
        # Every integer but the largest UInt64 values is an Int. Those raise here,
        # and they fit no class that reaches this line.
        via = "Int.from(value)"
    return f"    {mark}{head} {{\n        return {method}({via});\n    }}\n"


def conversions(name, method, machine):
    return "\n".join(conversion(name, src, method, machine) for src in ALL)


HEADER = "// Generated by compiler/tools/gen_numbers.py. Edit the generator, not this file.\npackage cleat;\n\n"

# What every class that has `lessThan` gets from it.
ORDERED_BY_LESS_THAN = """
    @Override
    public Boolean atMost({n} other) {{
        return !(other < this);
    }}

    @Override
    public Boolean greaterThan({n} other) {{
        return other < this;
    }}

    @Override
    public Boolean atLeast({n} other) {{
        return !(this < other);
    }}

    @Override
    public Int compare({n} other) {{
        return this < other ? -1 : other < this ? 1 : 0;
    }}

    public {n} min({n} other) {{
        return this < other ? this : other;
    }}

    public {n} max({n} other) {{
        return this > other ? this : other;
    }}
"""

ZERO_AND_ONE = """
    @Override
    public static {n} zero() {{
        return 0;
    }}

    @Override
    public static {n} one() {{
        return 1;
    }}
"""

# Int and UInt64: the machine's operations, and the rest written over them.
WIDE = """    @Override
    @Intrinsic
    public {n} plus({n} other);

    @Override
    @Intrinsic
    public {n} minus({n} other);

    @Override
    @Intrinsic
    public {n} times({n} other);

    @Override
    public {n} negate() {{
        return zero() - this;
    }}
{zero_and_one}
    @Override
    @Intrinsic
    public Boolean lessThan({n} other);
{ordered}
    // The quotient rounded toward zero, and what is left of the dividend.
    @Intrinsic
    public {n} truncatingDiv({n} other);

    @Intrinsic
    public {n} truncatingRem({n} other);

    // The quotient rounded toward negative infinity: one less than the truncated
    // quotient when the division is inexact and the operands differ in sign.
    public {n} floorDiv({n} other) {{
        var quotient = truncatingDiv(other);
        var rest = truncatingRem(other);
        return rest != 0 && (rest < 0) != (other < 0) ? quotient - 1 : quotient;
    }}

    // Zero, or a value with the sign of the divisor.
    public {n} mod({n} other) {{
        var rest = truncatingRem(other);
        return rest != 0 && (rest < 0) != (other < 0) ? rest + other : rest;
    }}

    @Intrinsic
    public {n} wrappingPlus({n} other);

    @Intrinsic
    public {n} wrappingMinus({n} other);

    @Intrinsic
    public {n} wrappingTimes({n} other);

    @Intrinsic
    public {n} and({n} other);

    @Intrinsic
    public {n} or({n} other);

    @Intrinsic
    public {n} xor({n} other);

    public {n} complement() {{
        return this ^ {ones};
    }}

    @Intrinsic
    public {n} shiftLeft(Int count);

    @Intrinsic
    public {n} shiftRight(Int count);

    // The decimal digits, after a minus sign when the value is below zero. The digits
    // are taken from the value as it is, because the lowest Int has no negation.
    @Override
    public String toString() {{
        if (this == 0) {{
            return "0";
        }}
        var count = this < 0 ? 1 : 0;
        for (var rest = this; rest != 0; rest = rest.truncatingDiv(10)) {{
            count += 1;
        }}
        var chars = new Char[count];
        var left = this;
        for (var at = count - 1; left != 0; at--) {{
            var digit = Int.from(left.truncatingRem(10));
            chars[at] = Char.from(48 + (digit < 0 ? -digit : digit));
            left = left.truncatingDiv(10);
        }}
        if (this < 0) {{
            chars[0] = '-';
        }}
        return String.fromChars(chars, count);
    }}

    // The text of an integer in decimal, or null when the text is not one or is out of
    // range. A sign may come first.
    public static @Nullable {n} parse(String text) {{
        var negative = text.startsWith("-");
        var at = negative || text.startsWith("+") ? 1 : 0;
        if (at == text.length()) {{
            return null;
        }}
        {n} value = 0;
        try {{
            while (at < text.length()) {{
                var digit = text[at].code() - 48;
                if (digit < 0 || digit > 9) {{
                    return null;
                }}
                value = negative ? value * 10 - from(digit) : value * 10 + from(digit);
                at++;
            }}
        }} catch (ArithmeticException e) {{
            return null;
        }}
        return value;
    }}
"""

# The narrower integer classes: arithmetic in Int, and a conversion back.
NARROW_BODY = """    // The value of this class with the low {bits} bits of an Int. `from(Int)` is the
    // conversion that raises when the Int is out of range, and this one never raises.
    @Intrinsic
    private static {n} wrapping(Int value);

    @Override
    public {n} plus({n} other) {{
        return from(Int.from(this) + Int.from(other));
    }}

    @Override
    public {n} minus({n} other) {{
        return from(Int.from(this) - Int.from(other));
    }}

    @Override
    public {n} times({n} other) {{
        return from(Int.from(this) * Int.from(other));
    }}

    @Override
    public {n} negate() {{
        return from(-Int.from(this));
    }}
{zero_and_one}
    @Override
    public Boolean lessThan({n} other) {{
        return Int.from(this) < Int.from(other);
    }}
{ordered}
    public {n} floorDiv({n} other) {{
        return from(Int.from(this).floorDiv(Int.from(other)));
    }}

    public {n} mod({n} other) {{
        return from(Int.from(this).mod(Int.from(other)));
    }}

    public {n} truncatingDiv({n} other) {{
        return from(Int.from(this).truncatingDiv(Int.from(other)));
    }}

    public {n} truncatingRem({n} other) {{
        return from(Int.from(this).truncatingRem(Int.from(other)));
    }}

    public {n} wrappingPlus({n} other) {{
        return wrapping(Int.from(this) + Int.from(other));
    }}

    public {n} wrappingMinus({n} other) {{
        return wrapping(Int.from(this) - Int.from(other));
    }}

    public {n} wrappingTimes({n} other) {{
        return wrapping(Int.from(this) * Int.from(other));
    }}

    public {n} and({n} other) {{
        return wrapping(Int.from(this) & Int.from(other));
    }}

    public {n} or({n} other) {{
        return wrapping(Int.from(this) | Int.from(other));
    }}

    public {n} xor({n} other) {{
        return wrapping(Int.from(this) ^ Int.from(other));
    }}

    public {n} complement() {{
        return wrapping(~Int.from(this));
    }}

    // A count below zero, or not below the width of the class, raises.
    public {n} shiftLeft(Int count) {{
        if (count < 0 || count >= {bits}) {{
            throw new ArithmeticException("a shift count of " + count + " is not a value of a shift of this class");
        }}
        return wrapping(Int.from(this) << count);
    }}

    public {n} shiftRight(Int count) {{
        if (count < 0 || count >= {bits}) {{
            throw new ArithmeticException("a shift count of " + count + " is not a value of a shift of this class");
        }}
        return wrapping(Int.from(this) >> count);
    }}

    @Override
    public String toString() {{
        return Int.from(this).toString();
    }}

    // The text of an integer in decimal, or null when the text is not one or is out of
    // range. A sign may come first.
    public static @Nullable {n} parse(String text) {{
        var wide = Int.parse(text);
        if (wide == null || wide < {low} || wide > {high}) {{
            return null;
        }}
        return from(wide);
    }}
"""

FLOAT = """    @Override
    @Intrinsic
    public {n} plus({n} other);

    @Override
    @Intrinsic
    public {n} minus({n} other);

    @Override
    @Intrinsic
    public {n} times({n} other);

    @Override
    @Intrinsic
    public {n} div({n} other);

    // The value with the other sign. Subtracting from zero would lose the sign of zero.
    @Override
    @Intrinsic
    public {n} negate();
{zero_and_one}
    // False when either side is NaN.
    @Override
    @Intrinsic
    public Boolean lessThan({n} other);

    @Override
    @Intrinsic
    public Boolean atMost({n} other);

    @Override
    public Boolean greaterThan({n} other) {{
        return other < this;
    }}

    @Override
    public Boolean atLeast({n} other) {{
        return other <= this;
    }}

    // A total order in which NaN is greatest and the two zeros are equal.
    @Override
    public Int compare({n} other) {{
        if (this < other) {{
            return -1;
        }}
        if (other < this) {{
            return 1;
        }}
        if (isNaN()) {{
            return other.isNaN() ? 0 : 1;
        }}
        return other.isNaN() ? -1 : 0;
    }}

    // The order of IEEE 754 over every value, which tells the two zeros apart.
    @Intrinsic
    public Int totalOrder({n} other);

    @Intrinsic
    public {n} floor();

    @Intrinsic
    public {n} ceil();

    @Intrinsic
    public {n} truncate();

    @Intrinsic
    public {n} round();

    @Intrinsic
    public {n} sqrt();

    @Intrinsic
    public {n} abs();

    // NaN is the one value that is not at most itself.
    public Boolean isNaN() {{
        return !(this <= this);
    }}

    // An infinity less itself is NaN, and a finite value less itself is zero.
    public Boolean isInfinite() {{
        return !isNaN() && (this - this).isNaN();
    }}

    public {n} min({n} other) {{
        return this < other ? this : other;
    }}

    public {n} max({n} other) {{
        return this > other ? this : other;
    }}

    // The decimal digits of the value rounded to `places` digits after the point.
    @Intrinsic
    public String toFixed(Int places);

    @Intrinsic
    public static @Nullable {n} parse(String text);
"""

RATIONAL = """    @Override
    @Intrinsic
    public Rational plus(Rational other);

    @Override
    @Intrinsic
    public Rational minus(Rational other);

    @Override
    @Intrinsic
    public Rational times(Rational other);

    @Override
    @Intrinsic
    public Rational div(Rational other);

    @Override
    public Rational negate() {
        return zero() - this;
    }
{zero_and_one}
    @Override
    @Intrinsic
    public Boolean lessThan(Rational other);
{ordered}
    // The value in lowest terms. The denominator is positive.
    @Intrinsic
    public Rational numerator();

    @Intrinsic
    public Rational denominator();

    public Boolean isInteger() {
        return denominator() == one();
    }

    // The quotient rounded toward negative infinity.
    @Intrinsic
    public Rational floorDiv(Rational other);

    public Rational mod(Rational other) {
        return this - floorDiv(other) * other;
    }

    public Rational floor() {
        return floorDiv(one());
    }

    public Rational ceil() {
        return -(-this).floor();
    }

    public Rational truncate() {
        return this < zero() ? ceil() : floor();
    }

    // The nearest integer, ties to even.
    public Rational round() {
        var below = floor();
        var rest = this - below;
        Rational half = 0.5;
        if (rest < half) {
            return below;
        }
        if (rest > half) {
            return below + one();
        }
        return below.mod(2) == zero() ? below : below + one();
    }

    // The nearest multiple of ten to the power -places, ties to even.
    public Rational round(Int places) {
        Rational scale = 1;
        var count = places < 0 ? -places : places;
        for (var i = 0; i < count; i++) {
            scale = scale * 10;
        }
        return places < 0 ? (this / scale).round() * scale : (this * scale).round() / scale;
    }

    public Rational abs() {
        return this < zero() ? -this : this;
    }

    // The digits of round(places), with exactly `places` digits after the point.
    @Intrinsic
    public String toDecimal(Int places);

    // A decimal numeral or a fraction "a/b", or null when the text is neither.
    @Intrinsic
    public static @Nullable Rational parse(String text);
"""


def write(name, body):
    io.open(f"prelude/{name}.cleat", "w", encoding="utf-8", newline="\n").write(HEADER + body)


def integer(name):
    ordered = ORDERED_BY_LESS_THAN.format(n=name)
    zero_and_one = ZERO_AND_ONE.format(n=name)
    low, high = int_range(name)
    head = f"public value class {name} implements Numeric<{name}>, Ordered<{name}> {{\n    private {name} {{\n    }}\n\n"
    if name in NARROW:
        body = NARROW_BODY.format(n=name, bits=width(name), low=low, high=high, zero_and_one=zero_and_one, ordered=ordered)
        machine = ["Int"]
    else:
        # The complement of an Int is its bits with -1; of a UInt64, with every bit set.
        ones = "-1" if low < 0 else str(high)
        body = WIDE.format(n=name, ones=ones, zero_and_one=zero_and_one, ordered=ordered)
        # Int takes every narrower integer as it is, and checks the rest. UInt64 checks
        # an Int, and has its own way from the classes an Int cannot hold.
        machine = NARROW + ["UInt64", "Float64", "Rational"] if name == "Int" else ["Int", "Float64", "Rational"]
    write(name, head + body + "\n" + conversions(name, "from", machine) + "}\n")


for name in INTEGERS:
    integer(name)

for name in FLOATS:
    other = "Float64" if name == "Float32" else "Float32"
    # An Int and a UInt64 are converted in one step, because going through the other
    # float class would round twice.
    machine = ["Int", "UInt64", other, "Rational"]
    write(
        name,
        f"public value class {name} implements Divisible<{name}>, Ordered<{name}> {{\n"
        f"    private {name} {{\n    }}\n\n"
        + FLOAT.format(n=name, zero_and_one=ZERO_AND_ONE.format(n=name))
        + "\n"
        + conversions(name, "from", machine)
        + "\n"
        + conversions(name, "nearest", machine)
        + "}\n",
    )

write(
    "Rational",
    "public value class Rational implements Divisible<Rational>, Ordered<Rational> {\n"
    "    private Rational {\n    }\n\n"
    + RATIONAL.replace("{zero_and_one}", ZERO_AND_ONE.format(n="Rational")).replace("{ordered}", ORDERED_BY_LESS_THAN.format(n="Rational"))
    + "\n"
    + conversions("Rational", "from", ["Int", "UInt64", "Float64"])
    + "}\n",
)
