"""Writes the small, regular files of the prelude: the functional interfaces, the
exception classes and the annotations. The larger classes are written by hand.

Run from the repository root: python compiler/tools/prelude_core.py
"""
import io

F = {}

F["Iterable"] = """
public interface Iterable<out T> {
    Iterator<T> iterator();
}
"""
F["Iterator"] = """
public interface Iterator<out T> {
    Boolean hasNext();
    T next();
}
"""
F["Function0"] = """
public interface Function0<out R> {
    R invoke();
}
"""
F["Function1"] = """
public interface Function1<in A, out R> {
    R invoke(A a);
}
"""
F["Function2"] = """
public interface Function2<in A, in B, out R> {
    R invoke(A a, B b);
}
"""
F["Comparator"] = """
// An order on T: negative when `a` comes first, positive when `b` does, zero for a tie.
public interface Comparator<in T> {
    Int compare(T a, T b);
}
"""
F["Numeric"] = """
public interface Numeric<T> {
    T plus(T other);
    T minus(T other);
    T times(T other);
    T negate();
    static T zero();
    static T one();
}
"""
F["Divisible"] = """
public interface Divisible<T> extends Numeric<T> {
    T div(T other);
}
"""
F["Ordered"] = """
public interface Ordered<in T> {
    Boolean lessThan(T other);
    Boolean atMost(T other);
    Boolean greaterThan(T other);
    Boolean atLeast(T other);
    Int compare(T other);
}
"""

EXCEPTIONS = [
    "ArithmeticException",
    "ClassCastException",
    "IndexOutOfBoundsException",
    "IllegalArgumentException",
    "IllegalStateException",
    "IllegalAccessException",
    "AssertionException",
    "ClassInitializationException",
    "OutOfMemoryException",
    "CancellationException",
    "IOException",
]
for exc in EXCEPTIONS:
    F[exc] = f"""
public open class {exc} extends Throwable {{
    public {exc}() {{
        super();
    }}

    public {exc}(String message) {{
        super(message);
    }}

    public {exc}(String message, Throwable cause) {{
        super(message, cause);
    }}
}}
"""

F["Annotation"] = """
// Implemented by every annotation, and by nothing else.
public interface Annotation {
}
"""
F["Site"] = """
// Where a declaration annotation may be written.
public enum Site { TYPE, ANNOTATION, FIELD, METHOD, CONSTRUCTOR, PARAMETER }
"""
F["Target"] = """
@Target(Site.ANNOTATION)
public annotation Target(Site[] sites);
"""
F["Inherited"] = """
@Target(Site.ANNOTATION)
public annotation Inherited;
"""
F["Refines"] = """
@Target(Site.ANNOTATION)
public annotation Refines(Class[] above = {});
"""
F["Widens"] = """
@Target(Site.ANNOTATION)
public annotation Widens;
"""
F["Nullable"] = """
@Widens
public annotation Nullable;
"""
F["Narrows"] = """
@Target(Site.METHOD)
public annotation Narrows(Class qualifier);
"""
F["Override"] = """
@Target(Site.METHOD)
public annotation Override;
"""
F["Discardable"] = """
@Target(Site.METHOD)
public annotation Discardable;
"""
F["Implicit"] = """
@Target(Site.METHOD)
public annotation Implicit;
"""
F["Deprecated"] = """
@Target({Site.TYPE, Site.FIELD, Site.METHOD, Site.CONSTRUCTOR})
public annotation Deprecated(String message = "");
"""
F["Intrinsic"] = """
@Target({Site.METHOD, Site.CONSTRUCTOR})
public annotation Intrinsic;
"""
F["Symbol"] = """
@Target(Site.METHOD)
public annotation Symbol(String name);
"""

for name, body in F.items():
    io.open(f"prelude/{name}.cleat", "w", encoding="utf-8", newline="\n").write(
        "// Generated by compiler/tools/prelude_core.py. Edit the generator, not this file.\n"
        "package cleat;\n" + body
    )
print(len(F), "files")
